
# Load data


```{r}
library(tidyverse)
library(ggplot2)
library(corrplot)

```


```{r}
data <- read_csv("../data/diabetes_012_health_indicators_BRFSS2015.csv")

map_qualitative_columns <- function(data) {
  data$Diabetes_012 <- factor(data$Diabetes_012, levels = c(0, 1, 2), labels = c("No", "Prediabetes", "Diabetes"))
  data$HighBP <- factor(data$HighBP, levels = c(0, 1), labels = c("No", "Yes"))
  data$HighChol <- factor(data$HighChol, levels = c(0, 1), labels = c("No", "Yes"))
  data$CholCheck <- factor(data$CholCheck, levels = c(0, 1), labels = c("No", "Yes"))
  data$Smoker <- factor(data$Smoker, levels = c(0, 1), labels = c("No", "Yes"))
  data$Stroke <- factor(data$Stroke, levels = c(0, 1), labels = c("No", "Yes"))
  data$HeartDiseaseorAttack <- factor(data$HeartDiseaseorAttack, levels = c(0, 1), labels = c("No", "Yes"))
  data$PhysActivity <- factor(data$PhysActivity, levels = c(0, 1), labels = c("No", "Yes"))
  data$Fruits <- factor(data$Fruits, levels = c(0, 1), labels = c("No", "Yes"))
  data$Veggies <- factor(data$Veggies, levels = c(0, 1), labels = c("No", "Yes"))
  data$HvyAlcoholConsump <- factor(data$HvyAlcoholConsump, levels = c(0, 1), labels = c("No", "Yes"))
  data$AnyHealthcare <- factor(data$AnyHealthcare, levels = c(0, 1), labels = c("No", "Yes"))
  data$NoDocbcCost <- factor(data$NoDocbcCost, levels = c(0, 1), labels = c("No", "Yes"))
  data$GenHlth <- factor(data$GenHlth, levels = c(1, 2, 3, 4, 5), labels = c("Excellent", "Very Good", "Good", "Fair", "Poor"))
  data$DiffWalk <- factor(data$DiffWalk, levels = c(0, 1), labels = c("No", "Yes"))
  data$Sex <- factor(data$Sex, levels = c(0, 1), labels = c("Female", "Male"))
  data$Age <- factor(data$Age, levels = 1:13, labels = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80+"))
  data$Education <- factor(data$Education, levels = 1:6, labels = c("No School", "Elementary", "Some High School", "High School Graduate", "Some College", "College Graduate"))
  data$Income <- factor(data$Income, levels = 1:8, labels = c("<$10,000", "$10,000-$14,999", "$15,000-$19,999", "$20,000-$24,999", "$25,000-$34,999", "$35,000-$49,999", "$50,000-$74,999", ">$75,000"))
  return(data)
}

data_plot <- map_qualitative_columns(data)

```


# Violin plot


```{r}
quantitative_columns <- c("BMI", "MentHlth", "PhysHlth")

for (i in 1:(length(columns) - 1)) {
  for (j in (i + 1):length(columns)) {
    if (!(columns[i] %in% quantitative_columns) & columns[j] %in% quantitative_columns) {
      plot <- ggplot(data = data_plot, aes_string(x = columns[i], y = columns[j], fill = columns[i])) +
        geom_violin()
      print(plot)
    }
  }
}

```


```{r}
for (i in 1:(length(columns) - 1)) {
  for (j in (i + 1):length(columns)) {
    if (!(columns[i] %in% quantitative_columns) & columns[j] %in% quantitative_columns) {
      plot <- ggplot(data = data_plot, aes_string(x = columns[i], y = columns[j], fill = columns[i])) +
        geom_boxplot()
      print(plot)
    }
  }
}

```


```{r}
cor_data <- cor(data)
corrplot(cor_data)

```

